version: "3.8"

services:
  dns-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "53:53/udp"
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - dns-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - dns-network

volumes:
  redis-data:

networks:
  dns-network:
    driver: bridge
